#
# Sumit Sample multiple test cases
# Wed Nov 02 19:18:46 2016
#
--- 

name: Sumit multi test set
short-name: Sumit MTC
elapsed: 0:00:00
remaining: 5:00:00
running: false
scoreboard-freeze: 01:00:00

# default pc2 judging types
computer-judged: true
manual-review: true
send-prelim-judgement: true

languages:
  - name: Java
    active: true

  - name: GNU C++
    active: true

  - name: GNU C
    active: true

  - name: Perl
    active: true

problemset:
  - letter: A
    short-name: sumit

sites:
 - number: 1
   name: Site 1
   IP: localhost
   port: 50002

accounts:
  - account: TEAM
    site: 1
    count: 22

  - account: JUDGE
    site: 1
    count: 12

  - account: SCOREBOARD
    site: 1
    count: 1

  - account: FEEDER
    site: 1
    count: 1

auto-judging:
  - account: JUDGE
    site: 1
    number: 2,3
    letters: A
    enabled: yes

# EOF Contest Configuration
